/* The following code was generated by JFlex 1.4.3 on 12/16/14 10:20 PM */

package codechanger;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/16/14 10:20 PM from the specification file
 * <tt>lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner, Symbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYSTRING = 2;
  public static final int YYINITIAL = 0;
  public static final int YYCHAR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\77\1\1\1\0\1\3\1\2\22\0\1\3\1\67\1\12"+
    "\1\6\1\7\1\65\1\74\1\13\1\51\1\52\1\5\1\63\1\57"+
    "\1\64\1\61\1\4\1\11\11\10\1\62\1\60\1\71\1\66\1\72"+
    "\2\0\1\7\1\16\1\7\1\14\1\15\1\7\1\20\6\7\1\24"+
    "\3\7\1\22\1\7\1\23\1\17\5\7\1\55\1\76\1\56\1\75"+
    "\1\21\1\0\1\33\1\37\1\31\1\30\1\44\1\43\1\50\1\32"+
    "\1\27\1\7\1\46\1\40\1\7\1\35\1\26\2\7\1\34\1\41"+
    "\1\36\1\42\1\25\1\45\2\7\1\47\1\53\1\73\1\54\1\70"+
    "\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\1\1\5\2\6"+
    "\1\7\1\10\14\5\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\0\1\40\1\41\3\0\1\42\1\43"+
    "\1\0\2\44\3\5\1\45\14\5\1\0\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\61\1\62\1\63\1\64\1\65\1\66\1\67"+
    "\1\70\1\71\1\72\1\73\1\74\1\75\1\76\1\77"+
    "\1\100\1\0\2\5\1\101\10\5\1\102\3\5\1\103"+
    "\1\104\1\105\1\0\1\5\1\106\1\5\1\107\1\5"+
    "\1\110\4\5\1\111\1\5\1\112\3\5\1\113\2\5"+
    "\1\114\1\115\2\5\1\116\1\117\1\120\3\5\1\121"+
    "\3\5\1\122";

  private static int [] zzUnpackAction() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\300\0\u0100\0\u0140\0\u0180"+
    "\0\u01c0\0\u0200\0\u0240\0\300\0\300\0\300\0\u0280\0\u02c0"+
    "\0\u0300\0\u0340\0\u0380\0\u03c0\0\u0400\0\u0440\0\u0480\0\u04c0"+
    "\0\u0500\0\u0540\0\300\0\300\0\300\0\300\0\300\0\300"+
    "\0\300\0\300\0\u0580\0\300\0\u05c0\0\u0600\0\u0640\0\u0680"+
    "\0\u06c0\0\300\0\u0700\0\u0740\0\u0780\0\u07c0\0\u0800\0\u0840"+
    "\0\300\0\u0880\0\300\0\300\0\u08c0\0\u0900\0\u0940\0\300"+
    "\0\300\0\u01c0\0\300\0\u0980\0\u09c0\0\u0a00\0\u0a40\0\u0200"+
    "\0\u0a80\0\u0ac0\0\u0b00\0\u0b40\0\u0b80\0\u0bc0\0\u0c00\0\u0c40"+
    "\0\u0c80\0\u0cc0\0\u0d00\0\u0d40\0\u0d80\0\300\0\300\0\300"+
    "\0\300\0\300\0\300\0\300\0\300\0\300\0\u0dc0\0\300"+
    "\0\u0e00\0\300\0\300\0\300\0\300\0\300\0\300\0\300"+
    "\0\300\0\300\0\300\0\300\0\300\0\300\0\300\0\300"+
    "\0\u0e40\0\u0e80\0\u0ec0\0\u0200\0\u0f00\0\u0f40\0\u0f80\0\u0fc0"+
    "\0\u1000\0\u1040\0\u1080\0\u10c0\0\u0200\0\u1100\0\u1140\0\u1180"+
    "\0\300\0\300\0\300\0\u11c0\0\u1200\0\u0200\0\u1240\0\u0200"+
    "\0\u1280\0\u0200\0\u12c0\0\u1300\0\u1340\0\u1380\0\u0200\0\u13c0"+
    "\0\u0200\0\u1400\0\u1440\0\u1480\0\u0200\0\u14c0\0\u1500\0\u0200"+
    "\0\u0200\0\u1540\0\u1580\0\u0200\0\u0200\0\u0200\0\u15c0\0\u1600"+
    "\0\u1640\0\u0200\0\u1680\0\u16c0\0\u1700\0\u0200";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\5\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\10\12\1\20\1\12"+
    "\1\21\1\12\1\22\2\12\1\23\2\12\1\24\1\12"+
    "\1\25\1\26\1\27\1\30\1\31\2\12\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\4\1\5\1\60\2\0"+
    "\7\60\1\61\63\60\1\62\1\0\1\63\2\0\10\63"+
    "\1\64\62\63\1\65\102\0\1\5\102\0\1\66\1\67"+
    "\60\0\1\70\77\0\1\71\11\0\1\72\1\73\1\74"+
    "\75\72\7\0\3\12\2\0\35\12\37\0\2\13\75\0"+
    "\3\12\2\0\1\12\1\75\33\12\36\0\3\12\2\0"+
    "\12\12\1\76\22\12\36\0\3\12\2\0\21\12\1\77"+
    "\5\12\1\100\5\12\36\0\3\12\2\0\12\12\1\101"+
    "\3\12\1\102\16\12\36\0\3\12\2\0\30\12\1\103"+
    "\4\12\36\0\3\12\2\0\12\12\1\104\5\12\1\105"+
    "\14\12\36\0\3\12\2\0\13\12\1\106\6\12\1\107"+
    "\12\12\36\0\3\12\2\0\21\12\1\110\13\12\36\0"+
    "\3\12\2\0\12\12\1\111\22\12\36\0\3\12\2\0"+
    "\24\12\1\112\10\12\36\0\3\12\2\0\16\12\1\113"+
    "\16\12\36\0\3\12\2\0\12\12\1\114\22\12\110\0"+
    "\1\115\101\0\1\116\2\0\1\117\75\0\1\120\1\0"+
    "\1\121\3\0\1\122\73\0\1\123\77\0\1\124\77\0"+
    "\1\125\77\0\1\126\2\0\1\127\74\0\1\130\3\0"+
    "\1\131\73\0\1\132\4\0\1\133\72\0\1\134\5\0"+
    "\1\135\71\0\1\136\11\0\1\60\2\0\7\60\1\0"+
    "\63\60\14\0\1\137\21\0\1\140\1\141\1\142\37\0"+
    "\1\143\14\0\1\144\20\0\1\145\1\146\1\147\37\0"+
    "\1\150\1\0\1\66\1\5\1\6\75\66\100\151\1\0"+
    "\1\73\105\0\3\12\2\0\2\12\1\152\32\12\36\0"+
    "\3\12\2\0\13\12\1\153\21\12\36\0\3\12\2\0"+
    "\22\12\1\154\12\12\36\0\3\12\2\0\21\12\1\155"+
    "\13\12\36\0\3\12\2\0\17\12\1\156\15\12\36\0"+
    "\3\12\2\0\22\12\1\157\12\12\36\0\3\12\2\0"+
    "\12\12\1\160\22\12\36\0\3\12\2\0\30\12\1\161"+
    "\4\12\36\0\3\12\2\0\33\12\1\162\1\12\36\0"+
    "\3\12\2\0\20\12\1\163\14\12\36\0\3\12\2\0"+
    "\13\12\1\164\21\12\36\0\3\12\2\0\20\12\1\165"+
    "\14\12\36\0\3\12\2\0\25\12\1\166\7\12\36\0"+
    "\3\12\2\0\13\12\1\167\21\12\36\0\3\12\2\0"+
    "\22\12\1\170\12\12\110\0\1\171\104\0\1\172\77\0"+
    "\1\173\11\0\5\151\1\174\72\151\7\0\3\12\2\0"+
    "\3\12\1\175\31\12\36\0\3\12\2\0\14\12\1\176"+
    "\20\12\36\0\3\12\2\0\22\12\1\177\12\12\36\0"+
    "\3\12\2\0\20\12\1\200\14\12\36\0\3\12\2\0"+
    "\26\12\1\201\6\12\36\0\3\12\2\0\24\12\1\202"+
    "\10\12\36\0\3\12\2\0\17\12\1\203\15\12\36\0"+
    "\3\12\2\0\30\12\1\204\4\12\36\0\3\12\2\0"+
    "\26\12\1\205\6\12\36\0\3\12\2\0\12\12\1\206"+
    "\22\12\36\0\3\12\2\0\30\12\1\207\4\12\36\0"+
    "\3\12\2\0\24\12\1\210\10\12\36\0\3\12\2\0"+
    "\12\12\1\211\22\12\27\0\4\151\1\5\1\174\72\151"+
    "\7\0\3\12\2\0\4\12\1\212\30\12\36\0\3\12"+
    "\2\0\13\12\1\213\21\12\36\0\3\12\2\0\20\12"+
    "\1\214\14\12\36\0\3\12\2\0\32\12\1\215\2\12"+
    "\36\0\3\12\2\0\12\12\1\216\22\12\36\0\3\12"+
    "\2\0\15\12\1\217\17\12\36\0\3\12\2\0\21\12"+
    "\1\220\13\12\36\0\3\12\2\0\30\12\1\221\4\12"+
    "\36\0\3\12\2\0\5\12\1\222\27\12\36\0\3\12"+
    "\2\0\21\12\1\223\13\12\36\0\3\12\2\0\21\12"+
    "\1\224\13\12\36\0\3\12\2\0\27\12\1\225\5\12"+
    "\36\0\3\12\2\0\22\12\1\226\12\12\36\0\3\12"+
    "\2\0\6\12\1\227\26\12\36\0\3\12\2\0\26\12"+
    "\1\230\6\12\36\0\3\12\2\0\1\12\1\231\33\12"+
    "\36\0\3\12\2\0\30\12\1\232\4\12\36\0\3\12"+
    "\2\0\7\12\1\233\25\12\36\0\3\12\2\0\3\12"+
    "\1\234\31\12\36\0\3\12\2\0\6\12\1\235\26\12"+
    "\36\0\3\12\2\0\10\12\1\236\24\12\27\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5952];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\6\1\3\11\14\1\10\11\1\1\1\11"+
    "\5\1\1\11\6\1\1\11\1\0\2\11\3\0\2\11"+
    "\1\0\1\11\21\1\1\0\11\11\1\1\1\11\1\1"+
    "\17\11\1\0\17\1\3\11\1\0\42\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[158];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();
	char ch;
	int flag = 0;

	private void err(String message) {
		System.out.println("Scanning error in line " + yyline + ", column " + yycolumn + ": " + message);
	}

	private java_cup.runtime.Symbol tok(int kind) {
		return new java_cup.runtime.Symbol(kind, yyline, yycolumn);
	}

	private java_cup.runtime.Symbol tok(int kind, Object value) {
		return new java_cup.runtime.Symbol(kind, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 162) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 78: 
          { return tok(RETURN);
          }
        case 83: break;
        case 42: 
          { return tok(PTR);
          }
        case 84: break;
        case 81: 
          { return tok(CONTINUE);
          }
        case 85: break;
        case 15: 
          { return tok(COMMAR);
          }
        case 86: break;
        case 18: 
          { return tok(COLON);
          }
        case 87: break;
        case 82: 
          { return tok(DEBUG_RETURN);
          }
        case 88: break;
        case 11: 
          { return tok(LBRACE);
          }
        case 89: break;
        case 61: 
          { if (flag != 0) throw new RuntimeException("Char Err");
		else {
			ch = '\r'; flag = 1;
		}
          }
        case 90: break;
        case 74: 
          { return tok(GOTO);
          }
        case 91: break;
        case 17: 
          { return tok(DOT);
          }
        case 92: break;
        case 32: 
          { if (flag != 0) throw new RuntimeException("Char Err");
		else {
			ch = yytext().charAt(0); flag = 1;
		}
          }
        case 93: break;
        case 65: 
          { return tok(INT);
          }
        case 94: break;
        case 51: 
          { return tok(PARAOR);
          }
        case 95: break;
        case 41: 
          { return tok(SUB_ASSIGN);
          }
        case 96: break;
        case 28: 
          { return tok(AND);
          }
        case 97: break;
        case 67: 
          { return tok(ELLIPSIS);
          }
        case 98: break;
        case 49: 
          { return tok(SHR);
          }
        case 99: break;
        case 39: 
          { return tok(ADD_ASSIGN);
          }
        case 100: break;
        case 5: 
          { return tok(ID, yytext());
          }
        case 101: break;
        case 57: 
          { string.append('\n');
          }
        case 102: break;
        case 52: 
          { return tok(AND_ASSIGN);
          }
        case 103: break;
        case 55: 
          { string.append('\"');
          }
        case 104: break;
        case 71: 
          { return tok(CHAR);
          }
        case 105: break;
        case 77: 
          { return tok(WHILE);
          }
        case 106: break;
        case 23: 
          { return tok(NOT);
          }
        case 107: break;
        case 26: 
          { return tok(GT);
          }
        case 108: break;
        case 44: 
          { return tok(EQ);
          }
        case 109: break;
        case 72: 
          { return tok(BOOL);
          }
        case 110: break;
        case 16: 
          { return tok(SEMICOLON);
          }
        case 111: break;
        case 68: 
          { return tok(SHL_ASSIGN);
          }
        case 112: break;
        case 56: 
          { string.append('\r');
          }
        case 113: break;
        case 3: 
          { return tok(DIVIDE);
          }
        case 114: break;
        case 50: 
          { return tok(OR_ASSIGN);
          }
        case 115: break;
        case 76: 
          { return tok(UNION);
          }
        case 116: break;
        case 58: 
          { string.append('\t');
          }
        case 117: break;
        case 47: 
          { return tok(SHL);
          }
        case 118: break;
        case 25: 
          { return tok(LT);
          }
        case 119: break;
        case 10: 
          { return tok(RPAREN);
          }
        case 120: break;
        case 40: 
          { return tok(DEC);
          }
        case 121: break;
        case 29: 
          { return tok(XOR);
          }
        case 122: break;
        case 63: 
          { if (flag != 0) throw new RuntimeException("Char Err");
		else {
			ch = '\t'; flag = 1;
		}
          }
        case 123: break;
        case 22: 
          { return tok(ASSIGN);
          }
        case 124: break;
        case 54: 
          { return tok(XOR_ASSIGN);
          }
        case 125: break;
        case 34: 
          { return tok(DIV_ASSIGN);
          }
        case 126: break;
        case 43: 
          { return tok(MOD_ASSIGN);
          }
        case 127: break;
        case 8: 
          { flag = 0; yybegin(YYCHAR);
          }
        case 128: break;
        case 62: 
          { if (flag != 0) throw new RuntimeException("Char Err");
		else {
			ch = '\n'; flag = 1;
		}
          }
        case 129: break;
        case 27: 
          { return tok(OR);
          }
        case 130: break;
        case 4: 
          { return tok(TIMES);
          }
        case 131: break;
        case 30: 
          { string.append(yytext());
          }
        case 132: break;
        case 69: 
          { return tok(SHR_ASSIGN);
          }
        case 133: break;
        case 70: 
          { return tok(VOID);
          }
        case 134: break;
        case 14: 
          { return tok(RBRAKET);
          }
        case 135: break;
        case 9: 
          { return tok(LPAREN);
          }
        case 136: break;
        case 60: 
          { if (flag != 0) throw new RuntimeException("Char Err");
		else {
			ch = '\''; flag = 1;
		}
          }
        case 137: break;
        case 73: 
          { return tok(ELSE);
          }
        case 138: break;
        case 38: 
          { return tok(INC);
          }
        case 139: break;
        case 48: 
          { return tok(GE);
          }
        case 140: break;
        case 37: 
          { return tok(IF);
          }
        case 141: break;
        case 13: 
          { return tok(LBRAKET);
          }
        case 142: break;
        case 59: 
          { string.append('\\');
          }
        case 143: break;
        case 36: 
          { return tok(PREPROCESSOR, yytext());
          }
        case 144: break;
        case 1: 
          { throw new RuntimeException("Illegal character!");
          }
        case 145: break;
        case 64: 
          { if (flag != 0) throw new RuntimeException("Char Err");
		else {
			ch = '\\'; flag = 1;
		}
          }
        case 146: break;
        case 45: 
          { return tok(NE) ;
          }
        case 147: break;
        case 7: 
          { string.setLength(0); yybegin(YYSTRING);
          }
        case 148: break;
        case 66: 
          { return tok(FOR);
          }
        case 149: break;
        case 24: 
          { return tok(TIDLE);
          }
        case 150: break;
        case 31: 
          { yybegin(YYINITIAL); return tok(STRING, string.toString());
          }
        case 151: break;
        case 46: 
          { return tok(LE);
          }
        case 152: break;
        case 75: 
          { return tok(BREAK);
          }
        case 153: break;
        case 53: 
          { return tok(PARAAND);
          }
        case 154: break;
        case 6: 
          { return tok(NUM, new Integer(yytext()));
          }
        case 155: break;
        case 33: 
          { yybegin(YYINITIAL); flag = 0; return tok(CHARCONST, ch);
          }
        case 156: break;
        case 21: 
          { return tok(MOD);
          }
        case 157: break;
        case 80: 
          { return tok(STRUCT);
          }
        case 158: break;
        case 79: 
          { return tok(SIZEOF);
          }
        case 159: break;
        case 35: 
          { return tok(MUL_ASSIGN);
          }
        case 160: break;
        case 19: 
          { return tok(PLUS);
          }
        case 161: break;
        case 20: 
          { return tok(MINUS);
          }
        case 162: break;
        case 2: 
          { 
          }
        case 163: break;
        case 12: 
          { return tok(RBRACE);
          }
        case 164: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	{
		if (yystate() == YYSTRING) {
			err("String boarder doesn't match");
		}
		return tok(EOF, null);
	}
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
