
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 16 22:20:33 SGT 2014
//----------------------------------------------------

package codechanger;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int SHR_ASSIGN = 50;
  public static final int DIVIDE = 57;
  public static final int SHR = 38;
  public static final int XOR_ASSIGN = 53;
  public static final int SHL = 37;
  public static final int CHAR = 3;
  public static final int GE = 33;
  public static final int XOR = 62;
  public static final int LPAREN = 18;
  public static final int CONTINUE = 12;
  public static final int INT = 4;
  public static final int MINUS = 55;
  public static final int FOR = 11;
  public static final int PARAAND = 28;
  public static final int RPAREN = 19;
  public static final int AND = 60;
  public static final int SUB_ASSIGN = 45;
  public static final int NOT = 36;
  public static final int SEMICOLON = 25;
  public static final int SIZEOF = 17;
  public static final int LT = 34;
  public static final int OR = 61;
  public static final int ELLIPSIS = 42;
  public static final int BOOL = 5;
  public static final int INC = 39;
  public static final int LBRAKET = 22;
  public static final int RBRAKET = 23;
  public static final int NUM = 64;
  public static final int PLUS = 54;
  public static final int PREPROCESSOR = 63;
  public static final int ASSIGN = 43;
  public static final int IF = 8;
  public static final int ID = 65;
  public static final int PTR = 41;
  public static final int DOT = 26;
  public static final int LE = 32;
  public static final int ADD_ASSIGN = 44;
  public static final int EOF = 0;
  public static final int RETURN = 16;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 49;
  public static final int COMMAR = 24;
  public static final int TIDLE = 59;
  public static final int MOD = 58;
  public static final int BREAK = 13;
  public static final int VOID = 2;
  public static final int EQ = 30;
  public static final int MOD_ASSIGN = 48;
  public static final int DIV_ASSIGN = 47;
  public static final int TIMES = 56;
  public static final int COLON = 27;
  public static final int UNION = 7;
  public static final int LBRACE = 20;
  public static final int ELSE = 9;
  public static final int AND_ASSIGN = 51;
  public static final int GOTO = 14;
  public static final int CHARCONST = 67;
  public static final int WHILE = 10;
  public static final int OR_ASSIGN = 52;
  public static final int RBRACE = 21;
  public static final int NE = 31;
  public static final int MUL_ASSIGN = 46;
  public static final int STRING = 66;
  public static final int DEC = 40;
  public static final int STRUCT = 6;
  public static final int GT = 35;
  public static final int DEBUG_RETURN = 15;
  public static final int PARAOR = 29;
}

